### ISSUE TITLE
Does not work with clone fields

### ISSUE THREAD

**Issue by tyrann0us** [andrejpavlovic/acf-conditional-logic-advanced#2]
Field type clone (https://www.advancedcustomfields.com/resources/clone/) has been added in ACF `v5.4.0`.
Without further testing it seems the `hidden-by-conditional-logic-advanced` class doesn't get applied to the `acf-field`.

Note that the original "Conditional Logic" isn't available for clone fields either.

**Comment by andrejpavlovic** [comment]
It seems to be working fine to me. Maybe it will work for you in the latest release (1.1.1). If it still isn't working, please provide a minimal test case and I can look into it. An export of the relevant custom field groups would suffice.

**Comment by tyrann0us** [comment]
@andrejpavlovic, thanks for getting back to me.

According to the [`v1.1.1` changelog](https://github.com/andrejpavlovic/acf-conditional-logic-advanced/releases/tag/1.1.1) you completely removed `Conditional Logic Advanced` from clone fields. I'm going to close the issue for that reason.
