### ISSUE TITLE
No showing

### ISSUE THREAD

**Issue by groupewibi** [andrejpavlovic/acf-conditional-logic-advanced#3]
Hi. Great add on ACF. I was waiting for a long time. 
But issue is, i do not see anything. 
I have activate the plugin, no issue. but nothing coming up under conditional.

Im using : 
ACF Pro 5.6.9
Wordpress 4.9.4

Any hint ?

**Comment by andrejpavlovic** [comment]
Take a look at the screenshots. Do you see the new field?

**Comment by groupewibi** [comment]
Nothing no.

**Comment by andrejpavlovic** [comment]
What PHP version are you using?
Did you try disabling all other plugins?
Did you try installing a fresh version of wordpress and just ACF Pro and this plugin?

Here is what it should look like when editing a field group:
![screenshot](https://user-images.githubusercontent.com/983644/36946768-f8aa014a-1f8f-11e8-9254-64f26a72f5d5.png)

Can you send a screenshot of what you see when editing a field group on your installation?
Also a screenshot of all the plugins you have installed would also be useful?

**Comment by andrejpavlovic** [comment]
No response, closing.
