### ISSUE TITLE
Wish it worked with Custom Taxonomies..

### ISSUE THREAD

**Issue by IntrepidRealist** [andrejpavlovic/acf-conditional-logic-advanced#4]
Any way that could happen?

**Comment by andrejpavlovic** [comment]
I might have had that working somewhat originally, but I don't think it was foolproof. I'll add it to my todo list, but I probably won't work on it any time soon.

**Comment by IntrepidRealist** [comment]
Wow! Thanks for the reply. You are donating your time for this, you can take as long as you want! :)

**Comment by andrejpavlovic** [comment]
Feature has been implemented in latest version (1.1.0)

**Comment by IntrepidRealist** [comment]
This is AWESOME!! Thank you SO much!
