### ISSUE TITLE
Only works after save

### ISSUE THREAD

**Issue by jameelmoses** [andrejpavlovic/acf-conditional-logic-advanced#5]
The fields only conditionally show/hide after save

**Comment by andrejpavlovic** [comment]
Hmm, works for me on the latest WP/ACF/plugin.

Can I get the following:
WP version
ACF version and whether it is pro
plugin verison

**Comment by andrejpavlovic** [comment]
No feedback provided. Closing issue.

**Comment by JMarqz** [comment]
This happens to me with:
WP v5.0.3
ACF Pro v5.7.10
Plugin v1.1.3
